version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Pass@word'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports:
        - "5001:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secret

  product-service:
    image: ${REGISTRY:-realstate}/productapi:${PLATFORM:-linux}-${TAG:-latest}
    container_name: product-service
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        SQL_SERVER_CONNECTION: "Server=sqldata; Database=ProductDb; User=sa; Password=Pass@word;TrustServerCertificate=True;"
    build:
      context: .
      dockerfile: src/Products.Api/Dockerfile
    ports:
        - "5100:80"
        - "5150:443"
    depends_on:
      - sqldata
 
volumes:
  data:


